//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatchAndUs.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Host
    {
        [Key]
        public int Id { get; set; }
        public byte[] userHost { get; set; }
        public string vid_title { get; set; }
        public string onOff { get; set; }
        public string inviteCode { get; set; }
        public System.DateTime expiredTime { get; set; }
        public int maxUsers { get; set; }
        public string end { get; set; }
    }
}
