//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatchAndUs.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Video
    {
        public string vid_title { get; set; }
        [Key]
        public string video_path { get; set; }
        public string vid_fileName { get; set; }
        public string vid_description { get; set; }
        public string vid_image { get; set; }
    }
}
